# Generated by DevOS — multi-stage Next.js standalone build.
# Slim final image (~150 MB) that runs `node server.js` from the
# .next/standalone directory. Requires next.config.js to set
# `output: 'standalone'` (the standalone copy is a no-op otherwise).

# ── Stage 1: install deps ────────────────────────────────
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
# `npm ci` is strict + fast when the lockfile matches package.json.
# Forge can edit package.json (adding deps for a feature) without
# being allowed to regenerate package-lock.json (DONT_TOUCH rule),
# so the lockfile drifts on feature branches. Fall back to `npm
# install` so the build still completes — that's better than every
# branch preview going red the moment Forge adds a dependency.
RUN --mount=type=cache,target=/root/.npm \
    (npm ci --include=dev || npm install --include=dev)

# ── Stage 2: build ───────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Ensure public/ exists so the runner stage's COPY doesn't fail on
# projects that don't ship a public/ directory yet. Next.js doesn't
# require one — it's purely for static assets — so a missing public/
# is legitimate. mkdir -p is idempotent: no-op if it already exists.
RUN mkdir -p public
RUN npm run build

# ── Stage 3: runner ──────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user for the runtime
RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
