// Generated by DevOS — auto-reports uncaught errors to the DevOS
// monitoring page. Mount <DevOSErrorReporter /> once in your root
// layout. Re-installing this file from DevOS will overwrite it.

'use client';

import { useEffect, type ReactNode } from 'react';

const CAPTURE_URL = "https://devos.batilabs.ai/api/errors/capture";
const PROJECT_ID  = "a1f87fb7-ed06-43e8-a05a-1affd0889a36";

function send(err: unknown, extra: Record<string, unknown> = {}) {
  const e = err as Error;
  const body = {
    projectId: PROJECT_ID,
    type:      e?.name ?? 'Error',
    message:   (e?.message ?? String(err)).slice(0, 4000),
    stack:     e?.stack,
    url:       typeof window !== 'undefined' ? window.location.href : undefined,
    severity:  'high' as const,
    ...extra,
  };
  fetch(CAPTURE_URL, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body:    JSON.stringify(body),
    // No credentials — the capture endpoint is stateless.
    keepalive: true,
  }).catch(() => { /* swallow — never error-loop the reporter */ });
}

/** Mount once in your app's root layout. Listens for window-level
 *  errors + unhandled promise rejections and reports them to DevOS. */
export function DevOSErrorReporter() {
  useEffect(() => {
    const onError = (ev: ErrorEvent) => send(ev.error ?? ev.message);
    const onRej   = (ev: PromiseRejectionEvent) => send(ev.reason);
    window.addEventListener('error', onError);
    window.addEventListener('unhandledrejection', onRej);
    return () => {
      window.removeEventListener('error', onError);
      window.removeEventListener('unhandledrejection', onRej);
    };
  }, []);
  return null;
}

/** Optional React error boundary. Wrap any subtree you want isolated:
 *  render errors there report to DevOS AND show a fallback UI. */
export class DevOSErrorBoundary extends (require('react').Component as any) {
  state = { hasError: false };
  static getDerivedStateFromError() { return { hasError: true }; }
  componentDidCatch(error: unknown, info: { componentStack?: string }) {
    send(error, { componentStack: info?.componentStack });
  }
  render() {
    if ((this as any).state.hasError) {
      return ((this as any).props.fallback as ReactNode) ??
        require('react').createElement('div', { style: { padding: 16, color: '#B45309' } }, 'Something broke — the team has been notified.');
    }
    return (this as any).props.children;
  }
}

/** Manually report an error (e.g. from a catch block). */
export function reportError(err: unknown, extra: Record<string, unknown> = {}) {
  send(err, extra);
}
