// Generated by DevOS — server-side error reporter for Fastify /
// Express / any Node HTTP stack. Call reportError(err) from your
// error-handling middleware. Re-installing from DevOS overwrites this.

const CAPTURE_URL = "https://devos.batilabs.ai/api/errors/capture";
const PROJECT_ID  = "a1f87fb7-ed06-43e8-a05a-1affd0889a36";

export async function reportError(err: Error, extra: Record<string, unknown> = {}): Promise<void> {
  try {
    await fetch(CAPTURE_URL, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        projectId:   PROJECT_ID,
        type:        err?.name ?? 'Error',
        message:     (err?.message ?? String(err)).slice(0, 4000),
        stack:       err?.stack,
        severity:    'high',
        environment: process.env.NODE_ENV ?? undefined,
        ...extra,
      }),
    });
  } catch {
    // Swallow — never fail a request because the reporter couldn't
    // reach DevOS. The original error should still bubble up normally.
  }
}
